"""Rebuild all three format fixtures from formulas, without instrument input.

Run this file with Python. All dates, coordinates and physical quantities below
are synthetic format-test values, not measurements or instrument calibration.
"""
from __future__ import annotations

import math
from pathlib import Path
import struct


def fixtures() -> dict[str, bytes]:
    lines = [
        "Experiment\tbias spectroscopy",
        "Saved Date\t01.01.2000 00:00:00",
        "X (m)\t0", "Y (m)\t0", "Z (m)\t2e-8",
        "Comment\tSynthetic cubic spectrum; generated by generate.py",
        "", "[DATA]", "Bias calc (V)\tCurrent (A)\tCurrent [bwd] (A)",
    ]
    for i in range(200):
        v = -2.0 + 4.0 * i / 199
        current = 1e-10 * (v + v ** 3)
        lines.append(f"{v:.9e}\t{current:.9e}\t{0.98 * current:.9e}")
    dat = ("\r\n".join(lines) + "\r\n").encode("ascii")

    header = (
        ':NANONIS_VERSION:\n2\n:SCANIT_TYPE:\nFLOAT MSBFIRST\n'
        ':REC_DATE:\n01.01.2000\n:REC_TIME:\n00:00:00\n'
        ':ACQ_TIME:\n128\n:SCAN_PIXELS:\n256 256\n'
        ':SCAN_FILE:\nsynthetic.sxm\n:SCAN_TIME:\n0.25 0.25\n'
        ':SCAN_RANGE:\n1e-7 1e-7\n:SCAN_OFFSET:\n0 0\n'
        ':SCAN_ANGLE:\n0\n:SCAN_DIR:\ndown\n:BIAS:\n1\n'
        ':COMMENT:\nSynthetic plane plus sinusoidal texture; generated by generate.py\n'
        ':DATA_INFO:\nChannel\tName\tUnit\tDirection\tCalibration\tOffset\n'
        '30\tZ\tm\tboth\t1\t0\n0\tCurrent\tA\tboth\t1\t0\n\n'
        ':SCANIT_END:\n'
    ).encode("ascii")
    z, current = [], []
    for row in range(256):
        y = row / 255
        for col in range(256):
            x = col / 255
            z.append(3e-9 * x + 2e-9 * y + 8e-11 * math.sin(8 * math.pi * x)
                     * math.cos(6 * math.pi * y))
            current.append(1e-10 * (1 + 0.02 * math.sin(4 * math.pi * x)))
    def reversed_rows(values: list[float]) -> list[float]:
        return [value for row in range(256)
                for value in reversed(values[row * 256:(row + 1) * 256])]
    samples = z + reversed_rows(z) + current + reversed_rows(current)
    sxm = header + b"\x1a\x04" + struct.pack(f">{len(samples)}f", *samples)

    grid_header = (
        'Grid dim="3 x 3"\r\nGrid settings=0;0;2e-8;2e-8;0\r\n'
        'Filetype=Linear\r\nSweep Signal="Bias (V)"\r\n'
        'Fixed parameters="Sweep Start;Sweep End"\r\n'
        'Experiment parameters="X (m);Y (m);Z (m);Z offset (m);Settling time (s);'
        'Integration time (s);Z-Ctrl hold;Final Z (m);Scan:Current (A);Scan:Z (m)"\r\n'
        '# Parameters (4 byte)=12\r\nExperiment size (bytes)=204\r\n'
        'Points=51\r\nChannels="Current (A)"\r\n'
        'Experiment="Grid Spectroscopy"\r\nStart time="01.01.2000 00:00:00"\r\n'
        'End time="01.01.2000 00:00:01"\r\n'
        'Comment="Synthetic polynomial spectra; generated by generate.py"\r\n'
        ':HEADER_END:\r\n'
    ).encode("ascii")
    values = []
    for row in range(3):
        for col in range(3):
            values.extend([-1, 1, (col - 1) * 1e-8, (row - 1) * 1e-8,
                           2e-8, 0, 1e-3, 1e-3, 1, 2e-8, 1e-10, 2e-8])
            for i in range(51):
                v = -1 + 2 * i / 50
                values.append(1e-10 * (1 + 0.1 * (row + col)) * (v + v ** 3))
    grid = grid_header + struct.pack(f">{len(values)}f", *values)
    return {"bias_spectroscopy_200pt.dat": dat, "scan_topography.sxm": sxm,
            "grid_3x3_bias.3ds": grid}


if __name__ == "__main__":
    for name, raw in fixtures().items():
        (Path(__file__).parent / name).write_bytes(raw)
