import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/api/client";
import type { components } from "@/api/schema";
import { DegradedNote, ErrorNote, Section, Spinner } from "@/components/ui";
import { fmtTime } from "@/components/records/shared";
import { useRunTaskStore } from "@/components/agents/runTaskStore";

// 群聊记录: the durable multi-agent group-chat
// history, surfaced inside 实验记录 where the operator expects to find past
// runs. Read-only replay of GET /api/agents/group-conversations →
// GET /api/agents/group-transcript; resuming a chat stays on the Agents page
// (the list links there via the conversation id).
//
// Feedback 2026-07-27 #17 — "一个实验若干样品，一个样品若干群聊，所以这个层次
// 有问题". This pane used to be a FLAT list with an experiment-id badge, which
// showed the experiment and the chat as if they were adjacent and left the
// sample — the level the operator actually works at — out of the picture
// entirely. It now renders the real three levels: 实验 → 样品 → 群聊.
//
// Rows that predate the sample tag (or were started with nothing active) are
// NOT hidden: they collect in explicit 未归属 buckets, because a chat you can't
// find is worse than one filed under "don't know".

// The three fields are re-declared locally as optional so this pane compiles
// against either generation of schema.d.ts — openapi.json is regenerated by
// whichever change happens to touch it, and this pane must not go red waiting
// for that. The server always sends them.
type GroupConversation = components["schemas"]["GroupConversation"] & {
  sample_id?: string | null;
  experiment_name?: string | null;
  sample_name?: string | null;
};
type TranscriptEntry = components["schemas"]["TranscriptEntry"];

const NO_EXPERIMENT = "\0none-exp";
const NO_SAMPLE = "\0none-sample";

type SampleGroup = { key: string; label: string; hint: string; chats: GroupConversation[] };
type ExperimentGroup = {
  key: string;
  label: string;
  hint: string;
  samples: SampleGroup[];
  total: number;
};

/**
 * Bucket a flat, newest-first conversation list into 实验 → 样品 → 群聊.
 *
 * Insertion order is preserved at every level, so "most recently active first"
 * survives the grouping — an experiment sorts by its newest chat, and so does a
 * sample. Exported for the unit test that pins the hierarchy .
 */
export function groupByExperimentAndSample(
  conversations: GroupConversation[],
): ExperimentGroup[] {
  const byExp = new Map<string, ExperimentGroup>();
  for (const c of conversations) {
    const expKey = c.experiment_id || NO_EXPERIMENT;
    let exp = byExp.get(expKey);
    if (!exp) {
      exp = {
        key: expKey,
        label:
          expKey === NO_EXPERIMENT
            ? "未归属实验"
            : c.experiment_name || `实验 ${String(c.experiment_id).slice(0, 8)}`,
        hint: expKey === NO_EXPERIMENT ? "开始时没有进行中的实验" : String(c.experiment_id),
        samples: [],
        total: 0,
      };
      byExp.set(expKey, exp);
    }
    const sampleKey = c.sample_id || NO_SAMPLE;
    let sample = exp.samples.find((s) => s.key === sampleKey);
    if (!sample) {
      sample = {
        key: sampleKey,
        label:
          sampleKey === NO_SAMPLE
            ? "未归属样品"
            : c.sample_name || `样品 ${String(c.sample_id).slice(0, 8)}`,
        hint:
          sampleKey === NO_SAMPLE
            ? "开始时没有进行中的样品（或这是加入样品层级之前的旧记录）"
            : String(c.sample_id),
        chats: [],
      };
      exp.samples.push(sample);
    }
    sample.chats.push(c);
    exp.total += 1;
  }
  return [...byExp.values()];
}

const AGENT_LABEL: Record<string, string> = {
  _supervisor: "编排器",
  literature: "文献",
  experiment_design: "实验设计",
  instrument_control: "仪器控制",
  data_processing: "数据处理",
  paper_writing: "论文撰写",
  paper_review: "论文评审",
};

function agentLabel(id?: string | null): string {
  if (!id) return "系统";
  return AGENT_LABEL[id] ?? id;
}

export function GroupChatHistoryPane() {
  const [openId, setOpenId] = useState<string | null>(null);
  // Collapsed-by-exception, so the three levels are visible on arrival rather
  // than hidden behind a disclosure the operator has to discover.
  const [closedExps, setClosedExps] = useState<string[]>([]);
  const navigate = useNavigate();
  const switchConversation = useRunTaskStore((s) => s.switchConversation);
  const runningNow = useRunTaskStore((s) => s.running);

  // 继续此群聊: point the (module-scoped) run-task store at this conversation
  // and jump to the 智能体 page, where RunTaskPanel replays its transcript and
  // the next message resumes the SAME checkpointed thread. Read-only history
  // with no way back into the run was only half of #39.
  async function resume(conversationId: string) {
    await switchConversation(conversationId);
    navigate("/agents");
  }

  const q = useQuery({
    queryKey: ["group-conversations"],
    queryFn: async () => {
      const { data, error } = await api.GET("/api/agents/group-conversations");
      if (error) throw error;
      return data;
    },
    refetchInterval: 30_000,
  });

  if (q.isLoading) return <Spinner label="加载群聊历史…" />;
  if (q.isError) return <ErrorNote error={q.error} />;
  if (q.data?.degraded) return <DegradedNote what="群聊历史" />;

  const conversations = (q.data?.conversations ?? []) as GroupConversation[];
  const activeId = q.data?.active_conversation_id ?? null;
  const tree = groupByExperimentAndSample(conversations);

  return (
    <Section
      title={`群聊记录 (${conversations.length})`}
      subtitle="按 实验 → 样品 → 群聊 归置：一个实验下若干样品，一个样品下若干群聊。点击群聊展开完整回放；「▶ 继续此群聊」在「智能体」页续跑同一线程。"
    >
      {conversations.length === 0 ? (
        <p className="text-sm text-mast-muted">暂无群聊记录。</p>
      ) : (
        <div className="space-y-3">
          {tree.map((exp) => {
            const collapsed = closedExps.includes(exp.key);
            return (
              <section key={exp.key} className="rounded-lg border border-mast-border">
                {/* level 1 — 实验 */}
                <button
                  className="flex w-full items-center gap-2 rounded-t-lg bg-mast-bg/40 px-3 py-2 text-left hover:bg-mast-bg/60"
                  title={exp.hint}
                  onClick={() =>
                    setClosedExps((prev) =>
                      prev.includes(exp.key)
                        ? prev.filter((k) => k !== exp.key)
                        : [...prev, exp.key],
                    )
                  }
                >
                  <span className="w-3 text-[10px] text-mast-muted">
                    {collapsed ? "▶" : "▼"}
                  </span>
                  <span className="text-[11px] uppercase tracking-wide text-mast-muted">
                    实验
                  </span>
                  <span className="text-sm font-semibold text-mast-text">{exp.label}</span>
                  <span className="ml-auto text-[11px] text-mast-muted">
                    {exp.samples.length} 个样品 · {exp.total} 个群聊
                  </span>
                </button>

                {!collapsed &&
                  exp.samples.map((sample) => (
                    /* level 2 — 样品 */
                    <div key={sample.key} className="border-t border-mast-border">
                      <div
                        className="flex items-center gap-2 px-3 py-1.5 pl-6"
                        title={sample.hint}
                      >
                        <span className="text-[11px] uppercase tracking-wide text-mast-muted">
                          样品
                        </span>
                        <span className="text-[12.5px] font-medium text-mast-text">
                          {sample.label}
                        </span>
                        <span className="ml-auto text-[11px] text-mast-muted">
                          {sample.chats.length} 个群聊
                        </span>
                      </div>

                      {/* level 3 — 群聊 */}
                      <ul className="space-y-1 px-3 pb-2 pl-9">
                        {sample.chats.map((c) => (
                          <li
                            key={c.conversation_id}
                            className="rounded-md border border-mast-border"
                          >
                            <button
                              className="flex w-full flex-wrap items-center gap-2 px-2.5 py-1.5 text-left hover:bg-mast-bg/40"
                              onClick={() =>
                                setOpenId(
                                  openId === c.conversation_id ? null : c.conversation_id,
                                )
                              }
                            >
                              <span className="text-sm font-medium text-mast-text">
                                {c.title || "未命名群聊"}
                              </span>
                              {activeId === c.conversation_id && (
                                <span className="rounded bg-mast-warn-bg px-1.5 py-0.5 text-[10px] text-mast-warn">
                                  运行中
                                </span>
                              )}
                              <span className="ml-auto text-[11px] text-mast-muted">
                                {c.updated_at ? fmtTime(c.updated_at) : ""}
                              </span>
                              <span
                                role="button"
                                tabIndex={0}
                                title={
                                  runningNow
                                    ? "当前有群聊正在运行——请先中止它再恢复这一条"
                                    : "在智能体页恢复这个群聊（同一线程续跑）"
                                }
                                onClick={(e) => {
                                  e.stopPropagation();
                                  if (!runningNow) void resume(c.conversation_id);
                                }}
                                onKeyDown={(e) => {
                                  if (e.key === "Enter" && !runningNow) {
                                    e.stopPropagation();
                                    void resume(c.conversation_id);
                                  }
                                }}
                                className={
                                  runningNow
                                    ? "rounded-md border border-mast-border px-2 py-0.5 text-[11px] text-mast-muted/50"
                                    : "rounded-md border border-mast-border px-2 py-0.5 text-[11px] text-mast-muted hover:text-mast-text"
                                }
                              >
                                ▶ 继续此群聊
                              </span>
                            </button>
                            {openId !== c.conversation_id && c.last_message_preview && (
                              <p className="truncate px-2.5 pb-1.5 text-xs text-mast-muted">
                                {c.last_message_preview}
                              </p>
                            )}
                            {openId === c.conversation_id && (
                              <TranscriptView conversationId={c.conversation_id} />
                            )}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
              </section>
            );
          })}
        </div>
      )}
    </Section>
  );
}

function TranscriptView({ conversationId }: { conversationId: string }) {
  const q = useQuery({
    queryKey: ["group-transcript", conversationId],
    queryFn: async () => {
      const { data, error } = await api.GET("/api/agents/group-transcript", {
        params: { query: { conversation_id: conversationId } },
      });
      if (error) throw error;
      return data;
    },
  });

  if (q.isLoading) return <Spinner label="加载对话…" />;
  if (q.isError) return <ErrorNote error={q.error} />;

  const entries = (q.data?.entries ?? []) as TranscriptEntry[];
  if (entries.length === 0) {
    return <p className="px-3 pb-3 text-xs text-mast-muted">（空对话）</p>;
  }
  return (
    <div className="max-h-[420px] space-y-1.5 overflow-auto border-t border-mast-border px-3 py-2">
      {entries.map((e, i) => {
        const kind = (e as { kind?: string }).kind ?? "message";
        const agent = (e as { agent_id?: string }).agent_id;
        const text = (e as { text?: string }).text ?? "";
        const role = (e as { role?: string }).role ?? "";
        if (!text) return null;
        const isOperator = kind === "operator";
        return (
          <div key={i} className="text-xs leading-relaxed">
            <span
              className={
                isOperator
                  ? "font-semibold text-mast-accent"
                  : role === "tool"
                    ? "font-mono text-mast-muted"
                    : "font-semibold text-mast-text"
              }
            >
              {isOperator ? "用户" : agentLabel(agent)}
              {role === "tool" ? " · 工具" : ""}：
            </span>
            <span className="whitespace-pre-wrap break-words text-mast-muted">
              {text.length > 800 ? text.slice(0, 800) + " …[截断]" : text}
            </span>
          </div>
        );
      })}
    </div>
  );
}
